import { ProposalMock, PlatformStatsMock } from "./types/models";

export const MOCK_STATS: PlatformStatsMock = {
  total_funded: 1250000,
  active_projects: 42,
  verified_users: 12400,
  total_regions: 18,
  average_ai_integrity_score: 84,
};

export const MOCK_FEATURED_PROPOSALS: ProposalMock[] = [
  {
    id: "prop_1",
    creator_id: "principal_1",
    title: "Urban Reforestation Initiative",
    short_description: "Planting 500 indigenous trees across the industrial district to improve air quality and provide natural shade.",
    problem_statement: "The industrial district lacks green spaces, leading to heat island effects and poor air quality for local residents.",
    success_metric: "500 trees successfully planted and surviving after 6 months.",
    location: {
      lat: 40.7128,
      lng: -74.006,
      address_line_1: "Industrial Way",
      city: "Brooklyn",
      country: "USA",
      postal_code: "11201",
      formatted_address: "Industrial Way, Brooklyn, NY 11201, USA",
    },
    region_id: "region_nyc",
    funding_goal: 50000,
    current_funding: 32500,
    currency: "USD",
    line_item_budget: [],
    milestones: [],
    funder_pledges: [],
    status: "voting",
    ai_integrity_report: {
      fairness_score: 92,
      efficiency_score: 88,
      overall_score: 90,
      summary: "High social ROI with clear environmental benefits. Budget is realistic for the scale.",
      debate_logs: [],
      risk_factors: ["Maintenance during first summer"],
      positive_externalities: ["Air quality improvement", "Property value increase"],
    },
    voting_metrics: {
      total_votes: 850,
      quorum_reached: true,
      quorum_percentage: 6.8,
      approval_percentage: 74,
      yes_votes_weighted: 1200,
      no_votes_weighted: 200,
      abstain_votes_weighted: 50,
      voting_power_distribution: { experts: 400, locals: 600, general: 200 },
    },
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-15T12:00:00Z",
    tags: ["Environment", "Urban"],
  },
  {
    id: "prop_2",
    creator_id: "principal_2",
    title: "Community Solar Cooperative",
    short_description: "Establishing a community-owned solar array on the roof of the local library to provide cheap energy to low-income households.",
    problem_statement: "Energy costs are rising, disproportionately affecting local low-income families while large roof spaces remain unused.",
    success_metric: "Installation of a 50kW solar array providing energy to at least 20 households.",
    location: {
      lat: 52.52,
      lng: 13.405,
      address_line_1: "Hauptstraße 12",
      city: "Berlin",
      country: "Germany",
      postal_code: "10115",
      formatted_address: "Hauptstraße 12, 10115 Berlin, Germany",
    },
    region_id: "region_berlin",
    funding_goal: 120000,
    current_funding: 45000,
    currency: "EUR",
    line_item_budget: [],
    milestones: [],
    funder_pledges: [],
    status: "funding",
    ai_integrity_report: {
      fairness_score: 95,
      efficiency_score: 82,
      overall_score: 89,
      summary: "Excellent fairness profile. Efficiency is standard for solar installations in this region.",
      debate_logs: [],
      risk_factors: ["Long-term maintenance contract", "Grid connection delays"],
      positive_externalities: ["CO2 reduction", "Energy independence"],
    },
    voting_metrics: {
      total_votes: 1200,
      quorum_reached: true,
      quorum_percentage: 12,
      approval_percentage: 89,
      yes_votes_weighted: 2500,
      no_votes_weighted: 100,
      abstain_votes_weighted: 150,
      voting_power_distribution: { experts: 800, locals: 1500, general: 200 },
    },
    created_at: "2024-02-15T09:00:00Z",
    updated_at: "2024-03-20T15:30:00Z",
    tags: ["Energy", "Social Equity"],
  },
  {
    id: "prop_3",
    creator_id: "principal_3",
    title: "Coding for Kids Workshop",
    short_description: "A series of free weekend workshops for local school children to learn basic programming and logical thinking.",
    problem_statement: "Local schools lack technical curriculum, leaving children behind in the digital economy.",
    success_metric: "100 students completing a 12-week basic coding course.",
    location: {
      lat: -33.8688,
      lng: 151.2093,
      address_line_1: "25 Market St",
      city: "Sydney",
      country: "Australia",
      postal_code: "2000",
      formatted_address: "25 Market St, Sydney NSW 2000, Australia",
    },
    region_id: "region_sydney",
    funding_goal: 15000,
    current_funding: 15000,
    currency: "AUD",
    line_item_budget: [],
    milestones: [],
    funder_pledges: [],
    status: "in_progress",
    ai_integrity_report: {
      fairness_score: 88,
      efficiency_score: 96,
      overall_score: 92,
      summary: "Incredibly high efficiency. Low overhead with maximum educational impact.",
      debate_logs: [],
      risk_factors: ["Volunteer retention"],
      positive_externalities: ["Digital literacy", "Future workforce development"],
    },
    voting_metrics: {
      total_votes: 450,
      quorum_reached: true,
      quorum_percentage: 5.2,
      approval_percentage: 92,
      yes_votes_weighted: 800,
      no_votes_weighted: 20,
      abstain_votes_weighted: 30,
      voting_power_distribution: { experts: 300, locals: 400, general: 100 },
    },
    created_at: "2024-01-10T08:00:00Z",
    updated_at: "2024-02-28T11:00:00Z",
    tags: ["Education", "Technology"],
  },
];
